### ISSUE TITLE
Update Project

### ISSUE THREAD

**Issue by mp1pro** [iderezin/CodeAcademy#1]
To resume the review, update the project and comment below.

**Comment by iderezin** [comment]
I'm sorry... I don't understand? I'm new to all of this(github, programming, etc.) . I seemed to upload the project? Not sure if I'm supposed to generate a pull request? (it's grayed out). 

Update the project? To do what?

**Comment by mp1pro** [comment]
There is no project in your repository. Please contact your slack channel adviser or contact https://help.codecademy.com/hc/en-us/requests/new for help on submitting your final project here. I would not be able to help with the submission process.

**Comment by iderezin** [comment]
Thanks.. this stuff is about as far as intuitive as it can get... evidently I can't have the same repository name locally as I do on Github(I just assumed it would mirror the local directory by the same name)?  I got it up.. but it's under https://github.com/iderezin/CodeAcademyFinal .. is this ok? Or do you need me to delete the old repository and do it correctly?

**Comment by mp1pro** [comment]
Please place the project inthis repository. If your unable to do so, please contact your slack channel adviser or contact https://help.codecademy.com/hc/en-us/requests/new for help on getting a review especially If the project is in another repo.

**Comment by iderezin** [comment]
sigh.. I guess I'm learning github the hard way? Thanks for your patience.. it should be here...
